on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            arch: x86_64

          - name: linux-aarch64
            arch: aarch64

    steps:
      - name: Checkout TDLib
        uses: actions/checkout@v4
        with:
          repository: tdlib/td
          fetch-depth: 1
          path: td

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            cmake gperf \
            zlib1g-dev libssl-dev jq

      - name: Configure
        run: |
          cmake -S td -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build tdjson
        run: |
          cmake --build build --target tdjson -j$(nproc)

      - name: Collect tdjson
        run: |
          mkdir -p out
          find build -type f -name "libtdjson.so*" -exec cp {} out/ \;

      - name: Package
        run: |
          cd out
          tar -czf TDLib-tdjson-${{ matrix.name }}.tar.gz *

      - name: Get latest gotdbot release tag
        id: rel
        run: |
          TAG=$(curl -s \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | jq -r .tag_name)

          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "No release found in this repository"
            exit 1
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Upload asset to latest gotdbot release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.rel.outputs.tag }}
          files: |
            out/TDLib-tdjson-${{ matrix.name }}.tar.gz
